config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index,:new, :create, :show] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: "already exists in the list" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    movie = Movie.find(params[:bookmark][:movie_id])
    list = List.find(params[:list_id])
    bookmark = Bookmark.new(bookmark_params)
    bookmark.list = list
    bookmark.movie = movie
    bookmark.save

    redirect_to list_path(list)
  end

  def destroy
    list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, as: :select %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div id="main-banner" class="jumbotron">
  <h1>
    Watch List
  </h1>
</div>
<div class="navbar px-4">
  <h1>
    Watch List
  </h1>
  <%= link_to new_list_path do %>
    <span class="btn btn-secondary rounded">New List</span>
  <% end %>
</div>
<div class="container">
  <% @lists.each do |list| %>
    <div class="container">
      <%= link_to list.name, list_path(list) %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="navbar px-4">
  <%= link_to lists_path do %>
  <% end %>
  <%= link_to new_list_path do %>
    <span class="btn btn-secondary rounded">New List</span>
  <% end %>
</div>
<div class="container">
<h1>
  <%= @list.name %>
</h1>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li>
      <% movie = Movie.find(bookmark.movie_id) %>
      <%= movie.title %>
      <%= link_to list_bookmark_path(@list, bookmark), method: :delete,
            data: { confirm: "Are you sure?" } do %>
            delete 
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to "new", new_list_bookmark_path(@list) %>

<%= link_to "back to home", lists_path %>
</div>